openapi: 3.1.0
info:
  version: 1.0.0
  title: Phrase book API specifications
  contact:
    email: graziastracquadanio@gmail.com
  description: |
    The Phrase Book app is a web-based application that enables users to access a custom phrasebook, 
    containing phrases they have created.
tags:
  - name: User
    description: Operations about users.
  - name: Phrase
    description: Operations about the phrases.
  - name: Collection
    description: Operations about the collections.
components:
  schemas:
    User:
      type: object
      properties:
        username:
          description: User supplied username
          type: string
          minLength: 4
          example: HarryPotter
        firstName:
          description: User first name
          type: string
          minLength: 1
          example: Harry
        email:
          description: User email address
          type: string
          format: email
          minLength: 1
          example: harrypotter@hogwarts.com
